name: CI

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.org"
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    timeout-minutes: 10

    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Install dependencies
        run: make prepare

      - name: Lint
        run: make lint

      - name: Test
        run: make test
